server:
  port: 8087

spring:
  application:
    name: spring-statemachine-showcase

logging:
  file:
    name: logs/application.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
